##############################################################################################################
# Derived from https://github.com/wurstmeister/storm-docker and https://github.com/wurstmeister/kafka-docker
# Apache 2.0 License
# Purpose: To deploy a Storm-Kafka-Zookeeper in docker
# 
# Steps:
# 1. Download and install Docker 1.12 or higher
# 2. cd to the directory of this file
# 3. docker-compose up -d
##############################################################################################################
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - "2181:2181"
      - "22"
  nimbus:
    image: wurstmeister/storm-nimbus
    ports:
      - "49773:3773"
      - "49772:3772"
      - "49627:6627"
      - "22"
    links: 
      - zookeeper:zk
    depends_on:
      - zookeeper
  supervisor:
    image: wurstmeister/storm-supervisor
    ports:
      - "8000"
      - "22"
    links: 
      - nimbus:nimbus
      - zookeeper:zookeeper
      - kafka:kafka
      - mysqls:mysqls
      - api:api
    depends_on:
      - nimbus
      - zookeeper
      - kafka
      - mysqls
      - api
  stormui:
    image: wurstmeister/storm-ui
    ports:
      - "8084:8080"
      - "22"
    links: 
      - nimbus:nimbus
      - zookeeper:zk
    depends_on:
      - nimbus
  kafka:
      image: wurstmeister/kafka:0.8.2.2
      ports:
        - "9092"
      links:
        - zookeeper:zookeeper
      environment:
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        HOSTNAME_COMMAND: hostname
        KAFKA_CREATE_TOPICS: "logTopic:1:1,rulesTopic:1:1,templatesTopic:1:1"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
  mysqls:
      image: mysql:5.7.12
      ports:
        - "53306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  api:
      image: "hendrix-api:${HVERSION}"
      ports:
        - "9000:9000"
      environment:
        KAFKA_ADDRESS: kafka:9092
        MYSQL_ADDRESS: mysqls:3306
        MYSQL_ROOT_USERNAME: root
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      links:
        - kafka:kafka
        - mysqls:mysqls
      depends_on:
        - mysqls
        - kafka
  ui:
      image: "hendrix-ui:${HVERSION}"
      ports:
        - "8080:8080"
      links:
        - api:api
      environment:
        API_SERVER: api:9000
      depends_on:
        - api