# Topology definition
# name to be used when submitting
name: "HendrixRulesTopology"

# NOTE: We may want to consider some level of spring integration. For example, allowing component references
# to a spring `ApplicationContext`.

# topology configuration
# this will be passed to the submitter as a map of config options
#
config:
    topology.workers: 2
    store.sql.url: "${javax.persistence.jdbc.url}"
    store.username: "${javax.persistence.jdbc.user}"
    store.password: "${javax.persistence.jdbc.password}"
    store.sql.db: "${javax.persistence.jdbc.db}"
    rstore.type: "io.symcpe.hendrix.storm.SQLRulesStore"
    tstore.type: "io.symcpe.hendrix.storm.SQLRulesStore"
    rstore.sql.table: "rules_table"
    tstore.sql.table: "alert_template"
    rule.group.active: "true"
    log.slow: "1000"
    
#    ui.endpoint: "http://${ui.host.port}/api/receive/"

# Components
# Components are analagous to Spring beans. They are meant to be used as constructor,
# property(setter), and builder arguments.
#
# for the time being, components must be declared in the order they are referenced
components:
  - id: "stringScheme"
    className: "storm.kafka.StringScheme"

  - id: "stringMultiScheme"
    className: "backtype.storm.spout.SchemeAsMultiScheme"
    constructorArgs:
      - ref: "stringScheme"

  - id: "zkHosts"
    className: "storm.kafka.ZkHosts"
    constructorArgs:
      - "${kafka.zk.host}"
      
  - id: "metricSpoutConfig"
    className: "storm.kafka.SpoutConfig"
    constructorArgs:
      # brokerHosts
      - ref: "zkHosts"
      # topic
      - "metricTopic"
      # zkRoot
      - ""
      # id
      - "metricTopic"
    properties:
      - name: "ignoreZkOffsets"
        value: false
      - name: "bufferSizeBytes"
        value: 2097152
#      - name: "fetchMaxWait"
#        value:
      - name: "fetchSizeBytes"
        value: 2097152
      - name: "scheme"
        ref: stringMultiScheme

  - id: "logSpoutConfig"
    className: "storm.kafka.SpoutConfig"
    constructorArgs:
      # brokerHosts
      - ref: "zkHosts"
      # topic
      - "logTopic"
      # zkRoot
      - ""
      # id
      - "logTopic"
    properties:
      - name: "ignoreZkOffsets"
        value: false
      - name: "bufferSizeBytes"
        value: 2097152
#      - name: "fetchMaxWait"
#        value:
      - name: "fetchSizeBytes"
        value: 2097152
      - name: "scheme"
        ref: stringMultiScheme

  - id: "ruleSpoutConfig"
    className: "storm.kafka.SpoutConfig"
    constructorArgs:
      # brokerHosts
      - ref: "zkHosts"
      # topic
      - "ruleTopic"
      # zkRoot
      - ""
      # id
      - "ruleTopic"
    properties:
      - name: "ignoreZkOffsets"
        value: false
      - name: "bufferSizeBytes"
        value: 1048576
#      - name: "fetchMaxWait"
#        value:
      - name: "fetchSizeBytes"
        value: 1048576
      - name: "scheme"
        ref: stringMultiScheme

  - id: "templateSpoutConfig"
    className: "storm.kafka.SpoutConfig"
    constructorArgs:
      # brokerHosts
      - ref: "zkHosts"
      # topic
      - "templateTopic"
      # zkRoot
      - ""
      # id
      - "templateTopic"
    properties:
      - name: "ignoreZkOffsets"
        value: false
      - name: "bufferSizeBytes"
        value: 1048576
#      - name: "fetchMaxWait"
#        value:
      - name: "fetchSizeBytes"
        value: 1048576
      - name: "scheme"
        ref: stringMultiScheme
        
  - id: "topicSelector"
    className: "storm.kafka.bolt.selector.DefaultTopicSelector"
    constructorArgs:
      - "alertTopic"
  - id: "kafkaMapper"
    className: "io.symcpe.hendrix.storm.bolts.AlertTupleMapper"
    
  - id: "kafkaProducerProps"
    className: "java.util.Properties"
    configMethods:
      - name: "put"
        args:
          - "bootstrap.servers"
          - "${bootstrap.servers}"
      - name: "put"
        args:
          - "acks"
          - "1"
      - name: "put"
        args:
          - "key.serializer"
          - "org.apache.kafka.common.serialization.StringSerializer"
      - name: "put"
        args:
          - "value.serializer"
          - "org.apache.kafka.common.serialization.StringSerializer"

# spout definitions
spouts:
  - id: "logSpout"
    className: "storm.kafka.KafkaSpout"
    constructorArgs:
      - ref: "logSpoutConfig"

  - id: "metricSpout"
    className: "storm.kafka.KafkaSpout"
    constructorArgs:
      - ref: "metricSpoutConfig"

  - id: "ruleSpout"
    className: "storm.kafka.KafkaSpout"
    constructorArgs:
      - ref: "ruleSpoutConfig"

  - id: "templateSpout"
    className: "storm.kafka.KafkaSpout"
    constructorArgs:
      - ref: "templateSpoutConfig"

# bolt definitions
bolts:
    # ...
  - id: "interceptionBolt"
    className: "io.symcpe.hendrix.storm.bolts.InterceptionBolt"
    parallelism: 1

    # ...
  - id: "translatorBolt"
    className: "io.symcpe.hendrix.storm.bolts.JSONTranslatorBolt"
    parallelism: 1

    # ...
  - id: "templateComponent"
    className: "io.symcpe.hendrix.storm.bolts.TemplateTranslatorBolt"
    parallelism: 1

    # ...
  - id: "ruleComponent"
    className: "io.symcpe.hendrix.storm.bolts.RuleTranslatorBolt"
    parallelism: 1

    # ...
  - id: "ruleEngineBolt"
    className: "io.symcpe.hendrix.storm.bolts.RulesEngineBolt"
    parallelism: 1

    # ...
  - id: "alertViewerBolt"
    className: "io.symcpe.hendrix.storm.bolts.helpers.AlertViewerBolt"
    parallelism: 1

    # ...
  - id: "templatedAlertEngineBolt"
    className: "io.symcpe.hendrix.storm.bolts.TemplatedAlertingEngineBolt"
    parallelism: 1

    # ...
  - id: "errorBolt"
    className: "io.symcpe.hendrix.storm.bolts.ErrorBolt"
    parallelism: 1

    # ...
  - id: "printerBolt"
    className: "io.symcpe.hendrix.storm.bolts.helpers.PrinterBolt"
    parallelism: 1
    
  - id: "alertSinkBolt"
    className: "io.symcpe.hendrix.storm.bolts.KafkaBolt"
    parallelism: 1
    configMethods:
      - name: "withTopicSelector"
        args: [ref: "topicSelector"]
      - name: "withTupleToKafkaMapper"
        args: [ref: "kafkaMapper"]
      - name: "withProducerProperties"
        args: [ref: "kafkaProducerProps"]

#stream definitions
# stream definitions define connections between spouts and bolts.
# note that such connections can be cyclical
# custom stream groupings are also supported

streams:
  # Metric Spout
  - name: "Kafka->Interception" # name isn't used (placeholder for logging, UI, etc.)
    from: "metricSpout"
    to: "interceptionBolt"
    grouping:
      type: SHUFFLE

  # Log Spout
  - name: "Kafka->Interception" # name isn't used (placeholder for logging, UI, etc.)
    from: "logSpout"
    to: "interceptionBolt"
    grouping:
      type: SHUFFLE

  # Rule Spout
  - name: "Kafka Rules->Rule Translator"
    from: "ruleSpout"
    to: "ruleComponent"
    grouping:
      type: SHUFFLE
      
  - name: "Kafka Templates->Template Translator"
    from: "templateSpout"
    to: "templateComponent"
    grouping:
      type: SHUFFLE

  - name: "Interception->Translator"
    from: "interceptionBolt"
    to: "translatorBolt"
    grouping:
      type: SHUFFLE

  - name: "Translator->Rule Engine"
    from: "translatorBolt"
    to: "ruleEngineBolt"
    grouping:
      type: SHUFFLE
      
  - name: "Rule Engine->Templated Alert Engine"
    from: "ruleEngineBolt"
    to: "templatedAlertEngineBolt"
    grouping:
      type: SHUFFLE
      streamId: "alertStream"
      
  - name: "Templated Alert Engine->Printer"
    from: "templatedAlertEngineBolt"
    to: "printerBolt"
    grouping:
      type: SHUFFLE
      streamId: "alertStream"

  - name: "Templated Alert Engine->Alert Sink"
    from: "templatedAlertEngineBolt"
    to: "alertSinkBolt"
    grouping:
      type: SHUFFLE
      streamId: "alertStream"  

  - name: "Rule Translator->Rule Engine"
    from: "ruleComponent"
    to: "ruleEngineBolt"
    grouping:
      type: ALL
      streamId: "syncStream"
      
  - name: "Template Translator->Templated Alert Engine"
    from: "templateComponent"
    to: "templatedAlertEngineBolt"
    grouping:
      type: ALL
      streamId: "syncStream"

  - name: "Translator->Error"
    from: "translatorBolt"
    to: "errorBolt"
    grouping:
      type: SHUFFLE
      streamId: "errorStream"

  - name: "Rule Translator->Error"
    from: "ruleComponent"
    to: "errorBolt"
    grouping:
      type: SHUFFLE
      streamId: "errorStream"
      
  - name: "Rule Translator->Error"
    from: "ruleComponent"
    to: "errorBolt"
    grouping:
      type: SHUFFLE
      streamId: "errorStream"

  - name: "Rule Engine->Error"
    from: "ruleEngineBolt"
    to: "errorBolt"
    grouping:
      type: SHUFFLE
      streamId: "errorStream"
      
  - name: "Templated Alert Engine->Error"
    from: "templatedAlertEngineBolt"
    to: "errorBolt"
    grouping:
      type: SHUFFLE
      streamId: "errorStream"

  - name: "Error->Printer"
    from: "errorBolt"
    to: "printerBolt"
    grouping:
      type: SHUFFLE
      streamId: "kafkaErrorStream"